<?php
/**
 * @author Greenrivers Team
 * @copyright Copyright (c) 2021 Greenrivers
 * @package Greenrivers_DeliveryTime
 */

use Magento\Sales\Model\Order\Item;
use Magento\Sales\Block\Order\Email\Items\DefaultItems;
use Greenrivers\DeliveryTime\ViewModel\DeliveryTime;

/** @var DefaultItems $block */
$layout = $block->getLayout()->getUpdate()->getHandles()[0];

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();

/** @var $_item Item */
$_item = $block->getItem();
$orderItem = $_item->getOrderItem();
$orderItems = $orderItem->getOrder()->getAllItems();
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */
                        nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <?php if ($deliveryTime->canShowOnItems($layout, $orderItems)): ?>
        <td class="item-delivery-time"><?= $block->escapeHtml($deliveryTime->renderFromItem($orderItem)) ?></td>
    <?php endif; ?>
    <td class="item-qty"><?= (float)$_item->getQty() ?></td>
</tr>
