<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer;
use Magento\Sales\Model\Order\Invoice\Item;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var DefaultRenderer $block */
$layout = $block->getRequest()->getFullActionName();

/** @var Item $_item */
$_item = $block->getItem();
$items = $block->getInvoice()->getAllItems();
$orderItem = $_item->getOrderItem();
$orderItems = $block->getOrder()->getAllItems();
$block->setPriceDataObject($_item);

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
<td class="col-price">
    <?= $block->getColumnHtml($_item, 'price') ?>
</td>
<?php if ($deliveryTime->canShowOnItems($layout, $orderItems)): ?>
    <td class="col-delivery-time"><?= $block->escapeHtml($deliveryTime->renderFromItem($orderItem)) ?></td>
<?php endif; ?>
<td class="col-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
<td class="col-qty-invoice">
    <?php if ($block->canEditQty()): ?>
        <input type="text" class="input-text admin__control-text qty-input"
               name="invoice[items][<?= (int)$_item->getOrderItemId() ?>]"
               value="<?= (float)$_item->getQty() ?>"/>
    <?php else: ?>
        <?= (float)$_item->getQty() ?>
    <?php endif; ?>
</td>
<td class="col-subtotal">
    <?= $block->getColumnHtml($_item, 'subtotal') ?>
</td>
<td class="col-tax"><?= /* @noEscape */
    $block->displayPriceAttribute('tax_amount') ?></td>
<td class="col-discount"><?= /* @noEscape */
    $block->displayPriceAttribute('discount_amount') ?></td>
<td class="col-total last">
    <?= $block->getColumnHtml($_item, 'total') ?>
</td>
