<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

use Magento\GiftMessage\Helper\Message;
use Magento\Sales\Block\Order\Email\Items;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var Items $block */
$layout = $block->getLayout()->getUpdate()->getHandles()[0];

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= $block->escapeHtml(__('Items')) ?>
            </th>
            <?php if ($deliveryTime->canShowOnProducts($layout, $_items)): ?>
                <th class="item-delivery-time">
                    <?= $block->escapeHtml(__('Delivery Time')) ?>
                </th>
            <?php endif; ?>
            <th class="item-qty">
                <?= $block->escapeHtml(__('Qty')) ?>
            </th>
            <th class="item-price">
                <?= $block->escapeHtml(__('Price')) ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper(Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br/>
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br/><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
