<?php
/**
 * @author Greenrivers Team
 * @copyright Copyright (c) 2021 Greenrivers
 * @package Greenrivers_DeliveryTime
 */

// @codingStandardsIgnoreFile
use Magento\LayeredNavigation\Block\Navigation\State;
use Greenrivers\DeliveryTime\ViewModel\DeliveryTimeFilter;

/**
 * Category layered navigation state
 *
 * @var State $block
 */
$categoryId = $block->getLayer()->getCurrentCategory()->getId();

/** @var DeliveryTimeFilter $deliveryTimeFilter */
$deliveryTimeFilter = $block->getDeliveryTimeFilter();
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <div class="filter-current"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false }}'>
        <strong class="block-subtitle filter-current-subtitle"
                role="heading"
                aria-level="2"
                data-role="title"
                data-count="<?= /* @noEscape */
                count($_filters) ?>"><?= $block->escapeHtml(__('Now Shopping by')) ?></strong>
        <ol class="items">
            <?php foreach ($_filters as $_filter): ?>
                <?php if ($deliveryTimeFilter->isDeliveryTime($_filter)): ?>
                    <li class="item">
                        <span class="filter-label"><?= $block->escapeHtml(__($deliveryTimeFilter->getLabel())) ?></span>
                        <div class="delivery-time"
                             data-mage-init='{
                             "sliderRange": {
                                    "divSlider": ".delivery-time #slider-range",
                                    "inputValues": ".delivery-time #values",
                                    "aBtn": ".delivery-time #btn",
                                    "maxValue": <?= $deliveryTimeFilter->getMaxValue($categoryId) ?>,
                                    "dateUnit": <?= json_encode($deliveryTimeFilter->getDateUnit()) ?>
                                }
                             }'
                        >
                            <div data-role="content" class="filter-options-content">
                                <p>
                                    <input type="text" id="values" readonly style="border:0; font-weight:bold;">
                                </p>
                                <div id="slider-range"></div>
                                <p>
                                    <a id="btn" href="<?= $block->escapeUrl($deliveryTimeFilter->getUrl()) ?>">
                                        <span>Apply filter</span>
                                    </a>
                                </p>
                            </div>
                        </div>
                        <a class="action remove"
                           title="<?= $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>"
                           href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>">
                            <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                        </a>
                    </li>
                <?php else : ?>
                    <li class="item">
                        <span class="filter-label"><?= $block->escapeHtml(__($_filter->getName())) ?></span>
                        <span
                            class="filter-value"><?= $block->escapeHtml($block->stripTags($_filter->getLabel())) ?></span>
                        <?php
                        $clearLinkUrl = $_filter->getClearLinkUrl();
                        $currentFilterName = $block->escapeHtmlAttr(__($_filter->getName()) . " " . $block->stripTags($_filter->getLabel()));
                        if ($clearLinkUrl):
                            ?>
                            <a class="action previous" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Previous')) ?>">
                                <span><?= $block->escapeHtml(__('Previous')) ?></span>
                            </a>
                            <a class="action remove"
                               title="<?= $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>"
                               href="<?= $block->escapeUrl($clearLinkUrl) ?>">
                                <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                            </a>
                        <?php else: ?>
                            <a class="action remove" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                               title="<?= /* @noEscape */
                               $block->escapeHtmlAttr(__('Remove')) . " " . $currentFilterName ?>">
                                <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
                            </a>
                        <?php endif; ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>
