<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
use Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var DefaultRenderer $block */
$_item = $block->getItem();
$orderItem = $_item->getOrderItem();
$layout = $block->getRequest()->getFullActionName();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<tr>
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <?php if ($deliveryTime->isEnabledOnOrderItem($orderItem, $layout)) : ?>
        <td class="col-product"><?= $block->escapeHtml($deliveryTime->renderFromItem($orderItem)) ?></td>
    <?php endif; ?>
    <td class="col-ordered-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
    <td class="col-qty <?php if ($block->isShipmentRegular()) : ?>last<?php endif; ?>">
        <?php if ($block->canShipPartiallyItem()) : ?>
            <input type="text"
                   class="input-text admin__control-text qty-item"
                   name="shipment[items][<?= (int)$_item->getOrderItemId() ?>]"
                   value="<?= /* @noEscape */
                   $_item->getQty() * 1 ?>"/>
        <?php else : ?>
            <?= /* @noEscape */
            $_item->getQty() * 1 ?>
        <?php endif; ?>
    </td>
    <?php if (!$block->canShipPartiallyItem()) : ?>
        <td class="col-ship last">
            <input type="hidden" name="shipment[items][<?= (int)$_item->getOrderItemId() ?>]" value="0"/>
            <input type="checkbox"
                   name="shipment[items][<?= (int)$_item->getOrderItemId() ?>]"
                   value="<?= /* @noEscape */
                   $_item->getQty() * 1 ?>" checked/>
        </td>
    <?php endif; ?>
</tr>
