<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var DefaultRenderer $block */
$_item = $block->getItem();
$orderItem = $_item->getOrderItem();
$orderItems = $orderItem->getOrder()->getAllItems();
$layout = $block->getRequest()->getFullActionName();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<tr class="border">
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <?php if ($deliveryTime->canShowOnItems($layout, $orderItems)): ?>
        <td class="col-delivery-time"><?= $block->escapeHtml($deliveryTime->renderFromItem($orderItem)) ?></td>
    <?php endif; ?>
    <td class="col-qty last"><?= /* @noEscape */
        $_item->getQty() * 1 ?></td>
</tr>
