<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Sales\Block\Order\Email\Invoice\Items;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var Items $block */
$_invoice = $block->getInvoice();
$_order = $block->getOrder();
$layout = $block->getLayout()->getUpdate()->getHandles()[0];

/** @var DeliveryTime $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($_invoice && $_order) : ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= $block->escapeHtml(__('Items')) ?>
            </th>
            <?php if ($viewModel->isEnabled($layout)) : ?>
                <th class="item-delivery-time">
                    <?= $block->escapeHtml(__('Delivery Time')) ?>
                </th>
            <?php endif; ?>
            <th class="item-qty">
                <?= $block->escapeHtml(__('Qty')) ?>
            </th>
            <th class="item-subtotal">
                <?= $block->escapeHtml(__('Subtotal')) ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_invoice->getAllItems() as $_item) : ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('invoice_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
