<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var DefaultRenderer $block */
$_item = $block->getItem();
$_item->setStoreId($_item->getInvoice()->getStoreId());
$layout = $block->getRequest()->getFullActionName();
$block->setPriceDataObject($_item);

/** @var DeliveryTime $viewModel */
$viewModel = $block->getViewModel();
?>
<tr>
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-price">
        <?= $block->getColumnHtml($_item, 'price') ?>
    </td>
    <?php if ($viewModel->isEnabledOnItem($_item, $layout)): ?>
        <td class="col-delivery-time"><?= $block->escapeHtml($viewModel->renderFromItem($_item)) ?></td>
    <?php endif; ?>
    <td class="col-qty"><?= (float)$_item->getQty() ?></td>
    <td class="col-subtotal">
        <?= $block->getColumnHtml($_item, 'subtotal') ?>
    </td>
    <td class="col-tax"><?= /* @noEscape */
        $block->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discount"><?= /* @noEscape */
        $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?= $block->getColumnHtml($_item, 'total') ?>
    </td>
</tr>
