<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var DefaultRenderer $block */
$_item = $block->getItem();
$orderItem = $_item->getOrderItem();
$orderItems = $block->getOrder()->getAllItems();
$block->setPriceDataObject($_item);
$layout = $block->getRequest()->getFullActionName();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<tr>
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-price">
        <?= $block->getColumnHtml($_item, 'price') ?>
    </td>
    <?php if ($deliveryTime->canShowOnItems($layout, $orderItems)): ?>
        <td class="col-delivery-time"><?= $block->escapeHtml($deliveryTime->renderFromItem($orderItem)) ?></td>
    <?php endif; ?>
    <td class="col-ordered-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
    <?php if ($block->canParentReturnToStock($_item)): ?>
        <td class="col-return-to-stock">
            <?php if ($block->canReturnItemToStock($_item)): ?>
                <input type="checkbox"
                       class="admin__control-checkbox"
                       name="creditmemo[items][<?= (int)$_item->getOrderItemId() ?>][back_to_stock]"
                       value="1"<?php if ($_item->getBackToStock()): ?> checked<?php endif; ?>/>
                <label class="admin__field-label"></label>
            <?php endif; ?>
        </td>
    <?php endif; ?>
    <td class="col-refund col-qty">
        <?php if ($block->canEditQty()): ?>
            <input type="text"
                   class="input-text admin__control-text qty-input"
                   name="creditmemo[items][<?= (int)$_item->getOrderItemId() ?>][qty]"
                   value="<?= (float)$_item->getQty() ?>"/>
        <?php else: ?>
            <?= (float)$_item->getQty() ?>
        <?php endif; ?>
    </td>
    <td class="col-subtotal">
        <?= $block->getColumnHtml($_item, 'subtotal') ?>
    </td>
    <td class="col-tax-amount"><?= /* @noEscape */
        $block->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discont"><?= /* @noEscape */
        $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?= $block->getColumnHtml($_item, 'total') ?>
    </td>
</tr>
