<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Sales\Block\Adminhtml\Order\Invoice\View\Items;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/* @var Items $block */
$layout = $block->getRequest()->getFullActionName();
$orderItems = $block->getOrder()->getAllItems();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-invoice-tables">
        <thead>
        <tr class="headings">
            <th class="col-product"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
            <th class="col-price"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
            <?php if ($deliveryTime->canShowOnItems($layout, $orderItems)): ?>
                <th class="col-delivery-time">
                    <span><?= $block->escapeHtml($deliveryTime->getLabel()) ?></span>
                </th>
            <?php endif; ?>
            <th class="col-qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
            <th class="col-subtotal"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
            <th class="col-tax"><span><?= $block->escapeHtml(__('Tax Amount')) ?></span></th>
            <th class="col-discount"><span><?= $block->escapeHtml(__('Discount Amount')) ?></span></th>
            <th class="col-total last"><span><?= $block->escapeHtml(__('Row Total')) ?></span></th>
        </tr>
        </thead>
        <?php $_items = $block->getInvoice()->getAllItems() ?>
        <?php $i = 0;
        foreach ($_items as $_item): ?>
            <?php if ($_item->getOrderItem()->getParentItem()):
                continue;
            else:
                $i++;
            endif; ?>
            <tbody class="<?= /* @noEscape */
            $i % 2 ? 'even' : 'odd' ?>">
            <?= $block->getItemHtml($_item) ?>
            <?= $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
