<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer;
use Magento\Sales\Model\Order\Shipment\Item;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var DefaultRenderer $block */
$layout = $block->getRequest()->getFullActionName();

/** @var Item $_item */
$_item = $block->getItem();
$_order = $block->getItem()->getOrderItem()->getOrder();
$orderItem = $_item->getOrderItem();
$orderItems = $_order->getAllItems();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<tr id="order-item-row-<?= (int)$_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()) : ?>
            <dl class="item options">
                <?php foreach ($_options as $_option) : ?>
                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                            <?= $block->escapeHtml($_formatedOptionValue['value']) ?>
                            <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                        <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else : ?>
                        <dd><?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtmlAttr(__('SKU')) ?>"><?= /* @noEscape */
        $block->prepareSku($block->getSku()) ?></td>
    <?php if ($deliveryTime->canShowOnItems($layout, $orderItems)): ?>
        <td class="col delivery-time" data-th="<?= $block->escapeHtmlAttr(__('Delivery Time')) ?>">
            <?= $deliveryTime->renderFromItem($orderItem) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty Shipped')) ?>"><?= (int)$_item->getQty() ?></td>
</tr>
