<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Catalog\Block\Product\View;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var View $block */
$product = $block->getProduct();
$layout = $block->getRequest()->getFullActionName();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<?php if ($deliveryTime->canShowOnProduct($layout, $product)): ?>
    <div class="delivery-time">
        <div class="fieldset">
            <div class="field delivery_time">
                <label class="label" for="delivery-time">
                    <span><?= $deliveryTime->getLabel() ?>:</span>
                    <span class="value"><?= $deliveryTime->renderFromProduct($product) ?></span>
                </label>
            </div>
        </div>
    </div>
<?php endif; ?>
