<?php
/**
 * @author GreenRivers Team
 * @copyright Copyright (c) 2020 GreenRivers
 * @package GreenRivers_DeliveryTime
 */

use Magento\Catalog\Block\Product\View;
use GreenRivers\DeliveryTime\ViewModel\DeliveryTime;

/** @var View $block */
$product = $block->getProduct();
$layout = $block->getRequest()->getFullActionName();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<?php if ($deliveryTime->canShowOnProduct($layout, $product)): ?>
    <div class="delivery-time">
        <div class="fieldset">
            <div class="field delivery_time">
                <label class="label" for="delivery-time">
                    <span><?= $block->escapeHtml($deliveryTime->getLabel()) ?>:</span>
                    <span class="value"><?= $block->escapeHtml($deliveryTime->renderFromProduct($product)) ?></span>
                </label>
            </div>
        </div>
    </div>
<?php endif; ?>
