<?php
/**
 * @author Greenrivers Team
 * @copyright Copyright (c) 2021 Greenrivers
 * @package Greenrivers_DeliveryTime
 */

use Magento\Sales\Block\Order\Email\Shipment\Items;
use Greenrivers\DeliveryTime\ViewModel\DeliveryTime;

/** @var Items $block */
$_shipment = $block->getShipment();
$_order = $block->getOrder();
$orderItems = $_order->getAllItems();
$layout = $block->getLayout()->getUpdate()->getHandles()[0];

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<?php if ($_shipment && $_order): ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= $block->escapeHtml(__('Items')) ?>
            </th>
            <?php if ($deliveryTime->canShowOnItems($layout, $orderItems)): ?>
                <th class="item-delivery-time">
                    <?= $block->escapeHtml($deliveryTime->getLabel()) ?>
                </th>
            <?php endif; ?>
            <th class="item-qty">
                <?= $block->escapeHtml(__('Qty')) ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_shipment->getAllItems() as $_item): ?>
            <?php if (!$_item->getOrderItem()->getParentItem()): ?>
                <tbody>
                <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
