<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_DeliveryTime
 */

use Magento\Shipping\Block\Adminhtml\View\Items;
use Unexpected\DeliveryTime\ViewModel\DeliveryTime;

/** @var Items $block */
$layout = $block->getRequest()->getFullActionName();
$orderItems = $block->getOrder()->getAllItems();

/** @var DeliveryTime $deliveryTime */
$deliveryTime = $block->getDeliveryTime();
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-shipment-table">
        <thead>
        <tr class="headings">
            <th class="col-product"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
            <?php if ($deliveryTime->canShowOnItems($layout, $orderItems)) : ?>
                <th class="col-delivery-time">
                    <span><?= $block->escapeHtml($deliveryTime->getLabel()) ?></span>
                </th>
            <?php endif; ?>
            <th class="col-qty last"><span><?= $block->escapeHtml(__('Qty Shipped')) ?></span></th>
        </tr>
        </thead>
        <?php $_items = $block->getShipment()->getAllItems() ?>
        <?php $_i = 0;
        foreach ($_items as $_item) :
            if (!empty($_item->getOrderItem())) :
                if ($_item->getOrderItem()->getParentItem()) :
                    continue;
                endif;
                $_i++ ?>
                <tbody class="<?= /* @noEscape */
                $_i % 2 ? 'odd' : 'even' ?>">
                <?= $block->getItemHtml($_item) ?>
                <?= $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
</div>
